/*
 * AboutDialog.java
 *
 * Created on 11. listopad 2006, 21:22
 */

package cz.datesoft.stockAccounting;

/**
 *
 * @author  lemming2
 */
public class AboutWindow extends javax.swing.JDialog
{
  
  /** Creates new form AboutDialog */
  public AboutWindow(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
    
    setLocationByPlatform(true);
    setSize(700,360);
    
    // Set icon
    iconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/dolar.png")));
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconButton = new javax.swing.JButton();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        bClose = new javax.swing.JButton();
        jEditorPane2 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("O aplikaci");

        iconButton.setAlignmentX(0.5F);
        iconButton.setBorderPainted(false);
        iconButton.setFocusPainted(false);
        iconButton.setFocusable(false);

        jEditorPane1.setEditable(false);
        jEditorPane1.setBackground(new java.awt.Color(255, 255, 102));
        jEditorPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jEditorPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEditorPane1.setText("Akciové účetnictví verze 1.2.7  (C) 2020 Michal Kára (lemming@ucw.cz), minor bugfixes Karel Dusek (karel.dusek@gmail.com)\nDomovská stránka: http://lemming.ucw.cz/ucetnictvi/ Šířeno pod licencí GPL");
        jEditorPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jEditorPane1.setOpaque(false);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        bClose.setText("Zavřít");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });
        jPanel1.add(bClose, new java.awt.GridBagConstraints());

        jEditorPane2.setEditable(false);
        jEditorPane2.setBackground(java.awt.SystemColor.control);
        jEditorPane2.setBorder(null);
        jEditorPane2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jEditorPane2.setText("Upozornění: Použití tohoto programu je pouze na vlastní nebezpečí!\nAutor neručí za jeho metodickou ani výpočetní správnost!\n\nChanges:\n31.05.2021 - Pridana podpora importu z Trading 212\n\n01.01.2021 - Import/ IB Tradelog: oprava ktera neignoruje obchody  ktere maji jen 15 sloupce mimo 16\n                   - pridana podpora pro FOP_TRD (future options)\n                   - opraveno detekce CASH_TRD jako penize\n\nKnow bugs:\n                   - IBImport spatne priradi CASH_TRD jako Typ CP (STK_TRD) jako fyzicka osoba co nedela FOREX je to asi jedno\n\ta, ale je nutne takove ochody pak manualne zmenit.");
        jEditorPane2.setOpaque(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(iconButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jEditorPane1))
                    .add(jEditorPane2)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(iconButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .add(jEditorPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jEditorPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void bCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bCloseActionPerformed
  {//GEN-HEADEREND:event_bCloseActionPerformed
    setVisible(false);
  }//GEN-LAST:event_bCloseActionPerformed
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new AboutWindow(new javax.swing.JFrame(), true).setVisible(true);
      }
    });
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton iconButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
  
}
